apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - role.yaml
  - cluster-role.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - deployment.yaml
  - routes.yaml
  - service.yaml
  - oauth.secret.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
  - fetch-accelerators.rbac.yaml
  - fetch-hardwares.rbac.yaml
  - fetch-nim-account.rbac.yaml
images:
  - name: oauth-proxy
    newName: registry.redhat.io/openshift4/ose-oauth-proxy
    digest: sha256:bf0607d18ab1be9c433492ebd3b317a2692f0f9670f0b20abd085de1558083f8
